# Generated by Django 4.0.5 on 2022-06-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("numero_de_paginas", models.IntegerField()),
                ("editora", models.CharField(max_length=50)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
